# Generated by Django 3.1.1 on 2020-09-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=5)),
                ('symbol', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.IntegerField(unique=True)),
                ('is_master', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking_api_app.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking_api_app.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('conversion_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('origin_entity_id', models.PositiveIntegerField()),
                ('target_entity_id', models.PositiveIntegerField()),
                ('origin_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_transfers', to='banking_api_app.currency')),
                ('origin_entity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_transfers', to='contenttypes.contenttype')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_transfers', to='banking_api_app.currency')),
                ('target_entity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_transfers', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('expiration_date', models.DateTimeField()),
                ('ccv', models.IntegerField()),
                ('status', models.CharField(choices=[(0, 'Active'), (1, 'Blocked')], default='Active', max_length=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking_api_app.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking_api_app.user')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking_api_app.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
