# Generated by Django 3.1.1 on 2020-09-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[(0, 'Active'), (1, 'Blocked')], default=0, max_length=10),
        ),
    ]
