# Generated by Django 3.1.1 on 2020-09-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_api_app', '0002_auto_20200927_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Blocked', 'Blocked')], default='Blocked', max_length=10),
        ),
    ]
